---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Latest Pull Request

# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Markdown linter: https://github.com/DavidAnson/markdownlint
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the main branch #
######################################################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  validate:
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
      - run: cat ".github/super-linter.env" >> "$GITHUB_ENV"

      ################################
      # Run Linters against code base #
      ################################
      - name: Lint Code Base
        #
        # Use full version number to avoid cases when a next
        # released version is buggy
        # About slim image: https://github.com/github/super-linter#slim-image
        uses: github/super-linter/slim@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true

      - name: Setup Node v16 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0' # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Yarn v3
        uses: borales/actions-yarn@v3
        with:
          cmd: set version stable

      - name: Install dependencies
        uses: borales/actions-yarn@v3
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          cmd: install

      - name: Check internal links
        uses: borales/actions-yarn@v3
        with:
          cmd: test:links

      - name: Build site
        if: ${{ success() }}
        uses: borales/actions-yarn@v3
        with:
          cmd: build
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          # TODO: Remove these and get the keys from secrets (stage credentials)
          PLAYGROUND_CLIENT_ID: "playground-addon-service-stage"
          PLAYGROUND_CLIENT_SECRET: "s8e-UEJx1fJcrcoT3rZUjpGveVCRvF5T4INr"
          PLAYGROUND_AUTH_CODE: "eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEtc3RnMS1rZXktcGFjLTEuY2VyIiwia2lkIjoiaW1zX25hMS1zdGcxLWtleS1wYWMtMSIsIml0dCI6InBhYyJ9.eyJpZCI6InBsYXlncm91bmQtYWRkb24tc2VydmljZS1zdGFnZV9zdGciLCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiY2xpZW50X2lkIjoicGxheWdyb3VuZC1hZGRvbi1zZXJ2aWNlLXN0YWdlIiwidXNlcl9pZCI6InBsYXlncm91bmQtYWRkb24tc2VydmljZS1zdGFnZUBBZG9iZVNlcnZpY2UiLCJhcyI6Imltcy1uYTEtc3RnMSIsIm90byI6ZmFsc2UsInNjb3BlIjoic3lzdGVtIiwiY3JlYXRlZF9hdCI6IjE3NTgxODI5NTM4NTAifQ.xA-hOLyRsCxzyAjPTZl_f5md3aDPyVHXGV_7LVhnCrWV4h-sFlXmAph6cOobzNmfdXI88EsQ7z74FMH0myHH-_CakMo99V_ZLyu9ti6ubt8WouenG8MOMcmMqfpsXq6YEn9p1GArKMCQkWIl2SywmvInJiarIQpbHxSgcouagLsp3LKl7Dn06sjuy778oq0eEcm1dWsL0YWC4D1jQLEa6jesmyTDUMQCp915jBEw3WjJwPwgUpgNB9Qv2zR_0gWgxwa0rBHH4AEvBGa8cnTtjDyOA4VUTrC59B6NpgNh2Q8LEScbs9qHfiOU6OBeMdYWcu59amKvWjXMc1M_Z-lPOA"
          PLAYGROUND_API_KEY: "ffc-addon-service"
